name: 'tests'
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          - windows-latest
        python-version:
          - "3.12"

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@master"

      - name: "Set up Python"
        uses: "actions/setup-python@master"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install dependencies"
        run: |
          python -m pip install hatch

      - name: "Run hatch test script for ${{ matrix.python-version }}"
        run: |
          python -m hatch run test:test

      - name: "Upload coverage data"
        uses: actions/upload-artifact@master
        with:
          name: covdata
          path: coverage.xml

  coverage:
    name: Coverage
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@master"

      - uses: actions/download-artifact@v4
        with:
          name: covdata

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./coverage.xml
          #flags: unittests # optional
          name: codecov # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
